package com.neuronest.neuronest.WordScramble

// List<WordScramblePuzzle>
// Predefined Word Scramble puzzles.
// For brevity, this file includes 25 sample puzzles; extend to 100 as required.
object WordScramblePuzzleData {
    val puzzles: List<WordScramblePuzzle> = listOf(
        // ---------- EASY (1–30) ----------
        WordScramblePuzzle(1, "CAT", "TAC", "Animals"),
        WordScramblePuzzle(2, "DOG", "GDO", "Animals"),
        WordScramblePuzzle(3, "ANT", "TNA", "Animals"),
        WordScramblePuzzle(4, "EGG", "GEG", "Food"),
        WordScramblePuzzle(5, "MILK", "KLIM", "Food"),
        WordScramblePuzzle(6, "BEEF", "EFEB", "Food"),
        WordScramblePuzzle(7, "CODE", "EDOC", "Technology"),
        WordScramblePuzzle(8, "BYTE", "TYEB", "Technology"),
        WordScramblePuzzle(9, "DATA", "ATAD", "Technology"),
        WordScramblePuzzle(10, "STAR", "RATS", "Science"),
        WordScramblePuzzle(11, "ATOM", "MOTA", "Science"),
        WordScramblePuzzle(12, "CELL", "LLEC", "Science"),
        WordScramblePuzzle(13, "FISH", "HSIF", "Animals"),
        WordScramblePuzzle(14, "BIRD", "DRIB", "Animals"),
        WordScramblePuzzle(15, "CAKE", "EKAC", "Food"),
        WordScramblePuzzle(16, "RICE", "ECIR", "Food"),
        WordScramblePuzzle(17, "WIFI", "IIFW", "Technology"),
        WordScramblePuzzle(18, "APP", "PPA", "Technology"),
        WordScramblePuzzle(19, "MOON", "NOMO", "Science"),
        WordScramblePuzzle(20, "SUN", "NSU", "Science"),
        WordScramblePuzzle(21, "COW", "OWC", "Animals"),
        WordScramblePuzzle(22, "HEN", "NEH", "Animals"),
        WordScramblePuzzle(23, "TEA", "ATE", "Food"),
        WordScramblePuzzle(24, "SOUP", "PUOS", "Food"),
        WordScramblePuzzle(25, "TECH", "HCET", "Technology"),
        WordScramblePuzzle(26, "JAVA", "AVAJ", "Technology"),
        WordScramblePuzzle(27, "MARS", "SRAM", "Science"),
        WordScramblePuzzle(28, "ROCK", "KCOR", "Science"),
        WordScramblePuzzle(29, "LION", "NOIL", "Animals"),
        WordScramblePuzzle(30, "BEAR", "RAEB", "Animals"),

        // ---------- MEDIUM (31–70) ----------
        WordScramblePuzzle(31, "TIGER", "GRITE", "Animals"),
        WordScramblePuzzle(32, "RABBIT", "TBARBI", "Animals"),
        WordScramblePuzzle(33, "MONKEY", "NOKMEY", "Animals"),
        WordScramblePuzzle(34, "PIZZA", "ZAZIP", "Food"),
        WordScramblePuzzle(35, "PASTA", "SATAP", "Food"),
        WordScramblePuzzle(36, "BURGER", "REGURB", "Food"),
        WordScramblePuzzle(37, "SERVER", "REVRES", "Technology"),
        WordScramblePuzzle(38, "KOTLIN", "NILTOK", "Technology"),
        WordScramblePuzzle(39, "ANDROID", "DIORAND", "Technology"),
        WordScramblePuzzle(40, "PLANET", "LPNETA", "Science"),
        WordScramblePuzzle(41, "ENERGY", "YRENEG", "Science"),
        WordScramblePuzzle(42, "OXYGEN", "NEGXOY", "Science"),
        WordScramblePuzzle(43, "ELEPHANT", "NAPHTLEE", "Animals"),
        WordScramblePuzzle(44, "GIRAFFE", "FERFAGI", "Animals"),
        WordScramblePuzzle(45, "NOODLE", "ELDOON", "Food"),
        WordScramblePuzzle(46, "CHEESE", "SEEHCE", "Food"),
        WordScramblePuzzle(47, "NETWORK", "KROWTEN", "Technology"),
        WordScramblePuzzle(48, "DATABASE", "SEBATADA", "Technology"),
        WordScramblePuzzle(49, "GRAVITY", "YTVIARG", "Science"),
        WordScramblePuzzle(50, "ORBIT", "TIBOR", "Science"),
        WordScramblePuzzle(51, "LEOPARD", "DRAPOLE", "Animals"),
        WordScramblePuzzle(52, "PENGUIN", "NUGIPE", "Animals"),
        WordScramblePuzzle(53, "SALMON", "NOMLAS", "Food"),
        WordScramblePuzzle(54, "COFFEE", "EFCOFE", "Food"),
        WordScramblePuzzle(55, "SECURITY", "RUCITYES", "Technology"),
        WordScramblePuzzle(56, "INTERNET", "TENRITNE", "Technology"),
        WordScramblePuzzle(57, "ECLIPSE", "PESLICE", "Science"),
        WordScramblePuzzle(58, "NEURON", "NROUEN", "Science"),
        WordScramblePuzzle(59, "WOLF", "FLOW", "Animals"),
        WordScramblePuzzle(60, "SHARK", "KRAHS", "Animals"),
        WordScramblePuzzle(61, "TACO", "OCAT", "Food"),
        WordScramblePuzzle(62, "BREAD", "REABD", "Food"),
        WordScramblePuzzle(63, "CLOUD", "UDLOC", "Technology"),
        WordScramblePuzzle(64, "ROUTER", "TREUOR", "Technology"),
        WordScramblePuzzle(65, "FUSION", "NUSOIF", "Science"),
        WordScramblePuzzle(66, "PLASMA", "MASLAP", "Science"),
        WordScramblePuzzle(67, "FOX", "XOF", "Animals"),
        WordScramblePuzzle(68, "OWL", "LWO", "Animals"),
        WordScramblePuzzle(69, "ICECREAM", "MECERIAC", "Food"),
        WordScramblePuzzle(70, "LASAGNA", "ANASLAG", "Food"),

        // ---------- HARD (71–100) ----------
        WordScramblePuzzle(71, "CHIMPANZEE", "ZPENMAIHCE", "Animals"),
        WordScramblePuzzle(72, "CROCODILE", "ELDROCOCI", "Animals"),
        WordScramblePuzzle(73, "CAPPUCCINO", "PICONACUCC", "Food"),
        WordScramblePuzzle(74, "CHOCOLATE", "TOCALOHEC", "Food"),
        WordScramblePuzzle(75, "MICROSERVICE", "CERSOMIVIEC", "Technology"),
        WordScramblePuzzle(76, "BLOCKCHAIN", "NIALHKCOCB", "Technology"),
        WordScramblePuzzle(77, "ASTROPHYSICS", "SPYTRCHASOIF", "Science"),
        WordScramblePuzzle(78, "THERMODYNAMICS", "MYNSATIDCOREHM", "Science"),
        WordScramblePuzzle(79, "HIPPOPOTAMUS", "POMATHUOPSIP", "Animals"),
        WordScramblePuzzle(80, "MEGABYTE", "TABEGYME", "Technology"),
        WordScramblePuzzle(81, "DEEPLEARNING", "PREENIALGEND", "Technology"),
        WordScramblePuzzle(82, "QUANTUM", "MUTNAUQ", "Science"),
        WordScramblePuzzle(83, "EVOLUTION", "NOITULOVE", "Science"),
        WordScramblePuzzle(84, "CHEETAH", "TACHEEH", "Animals"),
        WordScramblePuzzle(85, "BLUEBERRY", "REBLEURYB", "Food"),
        WordScramblePuzzle(86, "RASPBERRY", "RABPERSRY", "Food"),
        WordScramblePuzzle(87, "SUPERCOMPUTER", "RETMUPCOMREUS", "Technology"),
        WordScramblePuzzle(88, "BIOTECHNOLOGY", "GOLOTECHNITYB", "Technology"),
        WordScramblePuzzle(89, "COSMOLOGY", "SOOGCMYOL", "Science"),
        WordScramblePuzzle(90, "ELECTRONICS", "NOICETRCELE", "Science"),
        WordScramblePuzzle(91, "PLATYPUS", "SUPYTLAP", "Animals"),
        WordScramblePuzzle(92, "ARMADILLO", "LLODIARMA", "Animals"),
        WordScramblePuzzle(93, "CHEESEBURGER", "GRESEBRUEHC", "Food"),
        WordScramblePuzzle(94, "MOLECULAR", "RALUCOLEM", "Science"),
        WordScramblePuzzle(95, "NANOTECHNOLOGY", "GOLOTECHNOTYAN", "Technology"),
        WordScramblePuzzle(96, "GENETICS", "SCITENEG", "Science"),
        WordScramblePuzzle(97, "KOALA", "LAOAK", "Animals"),
        WordScramblePuzzle(98, "SANDWICH", "HCIDWNAS", "Food"),
        WordScramblePuzzle(99, "ALGORITHM", "HTIROGLAM", "Technology"),
        WordScramblePuzzle(100, "ASTRONAUT", "TUNARTSAO", "Science"),

        WordScramblePuzzle(101, "ROME", "EMOR", "Europe"),
        WordScramblePuzzle(102, "PARIS", "RISAP", "Europe"),
        WordScramblePuzzle(103, "MADRID", "RIDMAD", "Europe"),
        WordScramblePuzzle(104, "OSLO", "LOSO", "Europe"),
        WordScramblePuzzle(105, "VIENNA", "ANVEIN", "Europe"),
        WordScramblePuzzle(106, "PRAGUE", "EGUARP", "Europe"),
        WordScramblePuzzle(107, "TOKYO", "KOYOT", "Japan"),
        WordScramblePuzzle(108, "OSAKA", "KASAO", "Japan"),
        WordScramblePuzzle(109, "KYOTO", "TOYOK", "Japan"),
        WordScramblePuzzle(110, "NARA", "ARAN", "Japan"),
        WordScramblePuzzle(111, "MIAMI", "IAMIM", "USA"),
        WordScramblePuzzle(112, "TEXAS", "XETAS", "USA"),
        WordScramblePuzzle(113, "NEVADA", "DAVENA", "USA"),
        WordScramblePuzzle(114, "ALASKA", "SAKALA", "USA"),
        WordScramblePuzzle(115, "OHIO", "HOOI", "USA"),
        WordScramblePuzzle(116, "BONN", "NNOB", "Germany"),
        WordScramblePuzzle(117, "ESSEN", "NESSE", "Germany"),
        WordScramblePuzzle(118, "ULM", "LMU", "Germany"),
        WordScramblePuzzle(119, "PARK", "KRAP", "Places"),
        WordScramblePuzzle(120, "LAKE", "EKAL", "Places"),
        WordScramblePuzzle(121, "HILL", "LLIH", "Places"),
        WordScramblePuzzle(122, "ROAD", "ADOR", "Places"),
        WordScramblePuzzle(123, "PORT", "TROP", "Places"),
        WordScramblePuzzle(124, "ISLE", "ELSI", "Places"),
        WordScramblePuzzle(125, "BAY", "YAB", "Places"),
        WordScramblePuzzle(126, "CAVE", "EVAC", "Places"),
        WordScramblePuzzle(127, "DUNE", "NEDU", "Places"),
        WordScramblePuzzle(128, "RUINS", "SIRUN", "Places"),
        WordScramblePuzzle(129, "FORT", "TROF", "Places"),
        WordScramblePuzzle(130, "PLAZA", "ZALAP", "Places"),

        // ---------- MEDIUM (131–170) ----------
        WordScramblePuzzle(131, "BERLIN", "NIRBEL", "Germany"),
        WordScramblePuzzle(132, "HAMBURG", "GBURMAH", "Germany"),
        WordScramblePuzzle(133, "MUNICH", "HICNUM", "Germany"),
        WordScramblePuzzle(134, "STUTTGART", "TGARTTUS", "Germany"),
        WordScramblePuzzle(135, "FRANKFURT", "TURFNARKF", "Germany"),
        WordScramblePuzzle(136, "BREMEN", "NEMREB", "Germany"),
        WordScramblePuzzle(137, "DRESDEN", "NESDRDE", "Germany"),
        WordScramblePuzzle(138, "HANOVER", "REVOHAN", "Germany"),
        WordScramblePuzzle(139, "LEIPZIG", "GIZIPEL", "Germany"),
        WordScramblePuzzle(140, "KOBLENZ", "NEZLBOK", "Germany"),
        WordScramblePuzzle(141, "SEATTLE", "ETATLES", "USA"),
        WordScramblePuzzle(142, "CHICAGO", "OGCACHI", "USA"),
        WordScramblePuzzle(143, "BOSTON", "NOTSOB", "USA"),
        WordScramblePuzzle(144, "DENVER", "REVNED", "USA"),
        WordScramblePuzzle(145, "PHOENIX", "XHOPIEN", "USA"),
        WordScramblePuzzle(146, "DALLAS", "SLALAD", "USA"),
        WordScramblePuzzle(147, "AUSTIN", "NITSUA", "USA"),
        WordScramblePuzzle(148, "DETROIT", "TROITED", "USA"),
        WordScramblePuzzle(149, "ORLANDO", "NODARLO", "USA"),
        WordScramblePuzzle(150, "SANJOSE", "EJOSANS", "USA"),
        WordScramblePuzzle(151, "FUKUOKA", "KAFUOKU", "Japan"),
        WordScramblePuzzle(152, "NAGOYA", "AYOGAN", "Japan"),
        WordScramblePuzzle(153, "SENDAI", "IADENS", "Japan"),
        WordScramblePuzzle(154, "KOBE", "BEOK", "Japan"),
        WordScramblePuzzle(155, "HIROSHIMA", "RAMIHIOSH", "Japan"),
        WordScramblePuzzle(156, "YOKOHAMA", "MAHAYOKO", "Japan"),
        WordScramblePuzzle(157, "SAPPORO", "PROPOSA", "Japan"),
        WordScramblePuzzle(158, "NIKKO", "KONIK", "Japan"),
        WordScramblePuzzle(159, "IBARAKI", "KABIRAI", "Japan"),
        WordScramblePuzzle(160, "AKITA", "TAIKA", "Japan"),
        WordScramblePuzzle(161, "LONDON", "NODNOL", "Europe"),
        WordScramblePuzzle(162, "DUBLIN", "NILBUD", "Europe"),
        WordScramblePuzzle(163, "WARSAW", "SARWAW", "Europe"),
        WordScramblePuzzle(164, "ZURICH", "RCHUIZ", "Europe"),
        WordScramblePuzzle(165, "GENEVA", "AVENEG", "Europe"),
        WordScramblePuzzle(166, "LISBON", "NOSBIL", "Europe"),
        WordScramblePuzzle(167, "ATHENS", "SENTHA", "Europe"),
        WordScramblePuzzle(168, "SOFIA", "FAIOS", "Europe"),
        WordScramblePuzzle(169, "BRUSSELS", "LSSURESB", "Europe"),
        WordScramblePuzzle(170, "STOCKHOLM", "KLTOHMSOC", "Europe"),

        // ---------- HARD (171–200) ----------
        WordScramblePuzzle(171, "LOSANGELES", "SELAGNOSEL", "USA"),
        WordScramblePuzzle(172, "SANFRANCISCO", "COSNARFISNAS", "USA"),
        WordScramblePuzzle(173, "WASHINGTON", "GTNOSAHINW", "USA"),
        WordScramblePuzzle(174, "MASSACHUSETTS", "SETTSUACHAMSS", "USA"),
        WordScramblePuzzle(175, "CALIFORNIA", "NROFILACIA", "USA"),
        WordScramblePuzzle(176, "NEUSCHWANSTEIN", "NINATSECHWUSEN", "Germany"),
        WordScramblePuzzle(177, "BLACKFOREST", "KOTFERBSLAC", "Germany"),
        WordScramblePuzzle(178, "HEIDELBERG", "GREDLEBIEH", "Germany"),
        WordScramblePuzzle(179, "BRANDENBURG", "RUGBNERDANB", "Germany"),
        WordScramblePuzzle(180, "BUNDESLIGA", "GABLISEDUN", "Germany"),
        WordScramblePuzzle(181, "MOUNTFUJI", "UOJTMFNIU", "Japan"),
        WordScramblePuzzle(182, "SHINKANSEN", "NESHANKINS", "Japan"),
        WordScramblePuzzle(183, "CHERRYBLOSSOM", "MOSRLYBEOCHRS", "Japan"),
        WordScramblePuzzle(184, "TSUKIJI", "JITSUK", "Japan"),
        WordScramblePuzzle(185, "RYOKAN", "NORYAK", "Japan"),
        WordScramblePuzzle(186, "MEDITERRANEAN", "NARTEEMDAENRI", "Europe"),
        WordScramblePuzzle(187, "SCANDINAVIA", "AVANICSIDAN", "Europe"),
        WordScramblePuzzle(188, "BALKANPENINSULA", "SULPNANIKLEBAA", "Europe"),
        WordScramblePuzzle(189, "TRANSYLVANIA", "VALNAYTRSINA", "Europe"),
        WordScramblePuzzle(190, "AMSTERDAM", "RTASDEMM A", "Europe"),
        WordScramblePuzzle(191, "HIMALAYAS", "YAMALAHIS", "Places"),
        WordScramblePuzzle(192, "GREATBARRIERREEF", "FREGRETAIRBAEER", "Places"),
        WordScramblePuzzle(193, "GRANDCANYON", "YNOCDARNAG", "Places"),
        WordScramblePuzzle(194, "NIAGARAFALLS", "FASLAGRAIAN", "Places"),
        WordScramblePuzzle(195, "MACHUPICCHU", "CICHUMHPUAC", "Places"),
        WordScramblePuzzle(196, "ANTARCTICA", "CANTARITCA", "Places"),
        WordScramblePuzzle(197, "SAHARADESERT", "RATHDSAEERSA", "Places"),
        WordScramblePuzzle(198, "YELLOWSTONE", "NTSOYOLWLEE", "Places"),
        WordScramblePuzzle(199, "GALAPAGOS", "SGAOPALAG", "Places"),
        WordScramblePuzzle(200, "EVERESTBASECAMP", "PASTCMAESERBVE", "Places"),


        WordScramblePuzzle(201, "SONG", "GNOS", "Music"),
        WordScramblePuzzle(202, "DRUM", "MURD", "Music"),
        WordScramblePuzzle(203, "FLUTE", "TELUF", "Music"),
        WordScramblePuzzle(204, "VIOLA", "ALOIV", "Music"),
        WordScramblePuzzle(205, "OPERA", "AREPO", "Music"),
        WordScramblePuzzle(206, "CHOIR", "RIHOC", "Music"),
        WordScramblePuzzle(207, "DANCE", "CADNE", "Culture"),
        WordScramblePuzzle(208, "DRAMA", "MADAR", "Culture"),
        WordScramblePuzzle(209, "POET", "TEOP", "Culture"),
        WordScramblePuzzle(210, "NOVEL", "LNEVO", "Culture"),
        WordScramblePuzzle(211, "MYTH", "HTMY", "Culture"),
        WordScramblePuzzle(212, "FOLK", "KLOF", "Culture"),
        WordScramblePuzzle(213, "STONE", "ENOTS", "History"),
        WordScramblePuzzle(214, "SWORD", "DROWS", "History"),
        WordScramblePuzzle(215, "ARMOR", "MORAR", "History"),
        WordScramblePuzzle(216, "CROWN", "NWORC", "History"),
        WordScramblePuzzle(217, "ROYAL", "YALOR", "History"),
        WordScramblePuzzle(218, "RUINS", "SIRUN", "History"),
        WordScramblePuzzle(219, "RIVER", "REVIR", "Nature"),
        WordScramblePuzzle(220, "FOREST", "TSEROF", "Nature"),
        WordScramblePuzzle(221, "OCEAN", "NAECO", "Nature"),
        WordScramblePuzzle(222, "DESERT", "TREDES", "Nature"),
        WordScramblePuzzle(223, "GLACIER", "REICLAG", "Nature"),
        WordScramblePuzzle(224, "FLOWER", "WEROLF", "Nature"),
        WordScramblePuzzle(225, "SEED", "DEES", "Nature"),
        WordScramblePuzzle(226, "RAIN", "NIAR", "Nature"),
        WordScramblePuzzle(227, "WIND", "DNWI", "Nature"),
        WordScramblePuzzle(228, "FIRE", "ERIF", "Nature"),
        WordScramblePuzzle(229, "SNOW", "WONS", "Nature"),
        WordScramblePuzzle(230, "LEAF", "FAEL", "Nature"),

        // ---------- MEDIUM (231–270) ----------
        WordScramblePuzzle(231, "MELODY", "YLODEM", "Music"),
        WordScramblePuzzle(232, "RHYTHM", "HTHYMR", "Music"),
        WordScramblePuzzle(233, "HARMONY", "NYMORAH", "Music"),
        WordScramblePuzzle(234, "CONCERT", "CRETONC", "Music"),
        WordScramblePuzzle(235, "ORCHESTRA", "RACHTORES", "Music"),
        WordScramblePuzzle(236, "BALLET", "TELALB", "Culture"),
        WordScramblePuzzle(237, "THEATER", "RETHTAE", "Culture"),
        WordScramblePuzzle(238, "CINEMA", "ANEMIC", "Culture"),
        WordScramblePuzzle(239, "FESTIVAL", "TSAVIFEL", "Culture"),
        WordScramblePuzzle(240, "HERITAGE", "TIGAREHE", "Culture"),
        WordScramblePuzzle(241, "SCULPTURE", "TELRUPTUSC", "Culture"),
        WordScramblePuzzle(242, "PAINTING", "GNITNIPA", "Culture"),
        WordScramblePuzzle(243, "EMPIRE", "ERIPME", "History"),
        WordScramblePuzzle(244, "DYNASTY", "TSANDYY", "History"),
        WordScramblePuzzle(245, "REVOLT", "TLOVER", "History"),
        WordScramblePuzzle(246, "BATTLE", "TELTAB", "History"),
        WordScramblePuzzle(247, "ARCHIVE", "EVIHCRA", "History"),
        WordScramblePuzzle(248, "CHRONICLE", "LCIEHONCR", "History"),
        WordScramblePuzzle(249, "TIMELINE", "NEMILITE", "History"),
        WordScramblePuzzle(250, "ARTIFACT", "FTICARTA", "History"),
        WordScramblePuzzle(251, "VOLCANO", "NACLOVO", "Nature"),
        WordScramblePuzzle(252, "EARTHQUAKE", "KQEAHETURA", "Nature"),
        WordScramblePuzzle(253, "WATERFALL", "LTARFAWLE", "Nature"),
        WordScramblePuzzle(254, "RAINBOW", "OBWRANI", "Nature"),
        WordScramblePuzzle(255, "ECOSYSTEM", "YTSOMESCE", "Nature"),
        WordScramblePuzzle(256, "WILDLIFE", "ELIFDLWI", "Nature"),
        WordScramblePuzzle(257, "HURRICANE", "CNARURHEI", "Nature"),
        WordScramblePuzzle(258, "TORNADO", "OTANROD", "Nature"),
        WordScramblePuzzle(259, "AVALANCHE", "VLAANEC AH", "Nature"),
        WordScramblePuzzle(260, "CORALREEF", "FLEORRCAE", "Nature"),
        WordScramblePuzzle(261, "PERCUSSION", "CUSPRESONI", "Music"),
        WordScramblePuzzle(262, "KEYBOARD", "OBDRAEYK", "Music"),
        WordScramblePuzzle(263, "MICROPHONE", "ENHOPMICOR", "Music"),
        WordScramblePuzzle(264, "SYMPHONY", "NYOMHPSY", "Music"),
        WordScramblePuzzle(265, "SONGWRITER", "TREGNISORW", "Music"),
        WordScramblePuzzle(266, "VINYLRECORD", "DERYLCONIVR", "Music"),
        WordScramblePuzzle(267, "FOLKLORE", "ELORLKOF", "Culture"),
        WordScramblePuzzle(268, "STORYTELLER", "TELRETYROLS", "Culture"),
        WordScramblePuzzle(269, "CALLIGRAPHY", "PAGLHLARICY", "Culture"),
        WordScramblePuzzle(270, "TRADITION", "NOITIDART", "Culture"),

        // ---------- HARD (271–300) ----------
        WordScramblePuzzle(271, "ARCHAEOLOGY", "YGLOEOARHCA", "History"),
        WordScramblePuzzle(272, "CIVILIZATION", "NOITAZILIVIC", "History"),
        WordScramblePuzzle(273, "RENAISSANCE", "SSANIECNAER", "History"),
        WordScramblePuzzle(274, "INDUSTRIALIZATION", "NOITAZILARTSUDNI", "History"),
        WordScramblePuzzle(275, "MANUSCRIPT", "TPIRCNSUMA", "History"),
        WordScramblePuzzle(276, "HISTORIOGRAPHY", "YHPARGOIROTSIH", "History"),
        WordScramblePuzzle(277, "CLIMATECHANGE", "EGNAHCTAMICEL", "Nature"),
        WordScramblePuzzle(278, "BIODIVERSITY", "YTISREVODIBI", "Nature"),
        WordScramblePuzzle(279, "PHOTOSYNTHESIS", "SIHTESNYTOSOHP", "Nature"),
        WordScramblePuzzle(280, "DEFORESTATION", "NOITATSEROFED", "Nature"),
        WordScramblePuzzle(281, "ATMOSPHERIC", "CIRTSOHPTAME", "Nature"),
        WordScramblePuzzle(282, "OCEANOGRAPHY", "YHPARGONAECO", "Nature"),
        WordScramblePuzzle(283, "COMPOSITION", "NOITISOPMOC", "Music"),
        WordScramblePuzzle(284, "INSTRUMENTAL", "LATNEMURTSNI", "Music"),
        WordScramblePuzzle(285, "COUNTERPOINT", "TNIOPRETNUOC", "Music"),
        WordScramblePuzzle(286, "ELECTRONICMUSIC", "CISUMCINORTCELE", "Music"),
        WordScramblePuzzle(287, "ETHNOMUSICOLOGY", "YGLOOCISUMONHTE", "Music"),
        WordScramblePuzzle(288, "IMPROVISATION", "NOITASIVORPMI", "Music"),
        WordScramblePuzzle(289, "CULTURALIDENTITY", "YTITNEDILARUTLUC", "Culture"),
        WordScramblePuzzle(290, "SOCIALCUSTOMS", "SMOTSULCAICOS", "Culture"),
        WordScramblePuzzle(291, "ORALTRADITION", "NOITIDARTLARO", "Culture"),
        WordScramblePuzzle(292, "INTANGIBLEHERITAGE", "EGATIREHELBIGTNATNI", "Culture"),
        WordScramblePuzzle(293, "PERFORMINGARTS", "STRAGMNIFROPRE", "Culture"),
        WordScramblePuzzle(294, "FOLKMUSICTRADITION", "NOITIDARTCISUMKLOF", "Culture"),
        WordScramblePuzzle(295, "WORLDHERITAGESITE", "ETISGATIREHDLROW", "Culture"),
        WordScramblePuzzle(296, "SACREDLANDSCAPE", "EPACSCDNALDERAS", "Nature"),
        WordScramblePuzzle(297, "PALEOCLIMATOLOGY", "YGLOTAMICLOELAP", "Nature"),
        WordScramblePuzzle(298, "HISTORICALCHRONICLE", "ELCINORHC LACIROSITH", "History"),
        WordScramblePuzzle(299, "MUSICALCOMPOSITION", "NOITISOPMOC LACISUM", "Music"),
        WordScramblePuzzle(300, "INTERDISCIPLINARYART", "TRAILPNICSDERETNIRA", "Art"),


        WordScramblePuzzle(301, "YOGA", "AGOY", "Lifestyle"),
        WordScramblePuzzle(302, "GYM", "MYG", "Lifestyle"),
        WordScramblePuzzle(303, "DIET", "TIED", "Lifestyle"),
        WordScramblePuzzle(304, "SLEEP", "PEELS", "Lifestyle"),
        WordScramblePuzzle(305, "HABIT", "TIHAB", "Lifestyle"),
        WordScramblePuzzle(306, "STYLE", "ELTSY", "Lifestyle"),
        WordScramblePuzzle(307, "WORK", "KROW", "Business"),
        WordScramblePuzzle(308, "TRADE", "EDART", "Business"),
        WordScramblePuzzle(309, "SALES", "ELASS", "Business"),
        WordScramblePuzzle(310, "PROFIT", "TIFORP", "Business"),
        WordScramblePuzzle(311, "BRAND", "DNARB", "Business"),
        WordScramblePuzzle(312, "EMAIL", "LIAME", "Business"),
        WordScramblePuzzle(313, "TRAIN", "NIART", "Transport"),
        WordScramblePuzzle(314, "PLANE", "ENALP", "Transport"),
        WordScramblePuzzle(315, "METRO", "TOMER", "Transport"),
        WordScramblePuzzle(316, "FERRY", "YRREF", "Transport"),
        WordScramblePuzzle(317, "TRUCK", "KCURT", "Transport"),
        WordScramblePuzzle(318, "CARGO", "OGRAC", "Transport"),
        WordScramblePuzzle(319, "BOOK", "KOOB", "Education"),
        WordScramblePuzzle(320, "CLASS", "SSALC", "Education"),
        WordScramblePuzzle(321, "GRADE", "EDARG", "Education"),
        WordScramblePuzzle(322, "STUDY", "YDUTS", "Education"),
        WordScramblePuzzle(323, "EXAM", "MAXE", "Education"),
        WordScramblePuzzle(324, "LEARN", "NRLAE", "Education"),
        WordScramblePuzzle(325, "NOTES", "SETON", "Education"),
        WordScramblePuzzle(326, "TASK", "KSAT", "Education"),
        WordScramblePuzzle(327, "GOALS", "SLAOG", "Lifestyle"),
        WordScramblePuzzle(328, "ROUTINE", "ENITUOR", "Lifestyle"),
        WordScramblePuzzle(329, "CAREER", "REERAC", "Business"),
        WordScramblePuzzle(330, "SKILL", "LLIKS", "Education"),

        // ---------- MEDIUM (331–370) ----------
        WordScramblePuzzle(331, "MINDFUL", "LDFUNIM", "Lifestyle"),
        WordScramblePuzzle(332, "WELLNESS", "SSENLLEW", "Lifestyle"),
        WordScramblePuzzle(333, "BALANCE", "ECNALAB", "Lifestyle"),
        WordScramblePuzzle(334, "FITNESS", "SSENTIF", "Lifestyle"),
        WordScramblePuzzle(335, "NUTRITION", "NOITIRTUN", "Lifestyle"),
        WordScramblePuzzle(336, "FREELANCE", "ECNAELERF", "Business"),
        WordScramblePuzzle(337, "INVOICE", "ECIOVNI", "Business"),
        WordScramblePuzzle(338, "MARKETING", "GNITEKRAM", "Business"),
        WordScramblePuzzle(339, "FINANCE", "ECNANIF", "Business"),
        WordScramblePuzzle(340, "ECONOMY", "YMONOCE", "Business"),
        WordScramblePuzzle(341, "LOGISTICS", "SCITSIGOL", "Transport"),
        WordScramblePuzzle(342, "AIRPORT", "TROPRIA", "Transport"),
        WordScramblePuzzle(343, "HIGHWAY", "YAWGIHH", "Transport"),
        WordScramblePuzzle(344, "NAVIGATION", "NOITAGIVAN", "Transport"),
        WordScramblePuzzle(345, "SCHEDULE", "ELUDEHCS", "Transport"),
        WordScramblePuzzle(346, "DELIVERY", "YREVILED", "Transport"),
        WordScramblePuzzle(347, "SYLLABUS", "SUBALLYS", "Education"),
        WordScramblePuzzle(348, "LECTURE", "ERUTCEL", "Education"),
        WordScramblePuzzle(349, "HOMEWORK", "KROWEMOH", "Education"),
        WordScramblePuzzle(350, "CURRICULUM", "MULUCIRRUC", "Education"),
        WordScramblePuzzle(351, "ASSESSMENT", "TNEMSSS EAS", "Education"),
        WordScramblePuzzle(352, "CERTIFICATE", "ETACIFITREC", "Education"),
        WordScramblePuzzle(353, "INTERNSHIP", "PIHSNRETNI", "Education"),
        WordScramblePuzzle(354, "ENTREPRENEUR", "RUENEPERTNE", "Business"),
        WordScramblePuzzle(355, "LEADERSHIP", "PIHSREDAEL", "Business"),
        WordScramblePuzzle(356, "NEGOTIATION", "NOITAITOGEN", "Business"),
        WordScramblePuzzle(357, "SUPPLYCHAIN", "NIAHCLYPPUS", "Business"),
        WordScramblePuzzle(358, "COMMUTE", "ETUMMOC", "Transport"),
        WordScramblePuzzle(359, "URBANTRANSIT", "TISNARTNABRU", "Transport"),
        WordScramblePuzzle(360, "ELECTRICCAR", "RACCIRTCELE", "Transport"),
        WordScramblePuzzle(361, "TIME MANAGEMENT", "TNEMEGANAMEMIT", "Lifestyle"),
        WordScramblePuzzle(362, "SELFCARE", "ERACFLES", "Lifestyle"),
        WordScramblePuzzle(363, "ONLINELEARNING", "GNINRAELENILNO", "Education"),
        WordScramblePuzzle(364, "DISTANCELEARNING", "GNINRAELECNATSID", "Education"),
        WordScramblePuzzle(365, "CORPORATECULTURE", "ERUTLUCE TAROPROC", "Business"),
        WordScramblePuzzle(366, "PERSONALFINANCE", "ECNANIFLANOSREP", "Lifestyle"),
        WordScramblePuzzle(367, "CAREERDEVELOPMENT", "TNEMPOLEVEDREERAC", "Business"),
        WordScramblePuzzle(368, "PROJECTPLANNING", "GNINNALPTCEJORP", "Business"),
        WordScramblePuzzle(369, "PUBLICSPEAKING", "GNIKAEPS CILBUP", "Education"),
        WordScramblePuzzle(370, "KNOWLEDGESHARING", "GNIRAHSEGD E L W O N K", "Education"),

        // ---------- HARD (371–400) ----------
        WordScramblePuzzle(371, "LIFESTYLEOPTIMIZATION", "NOITAZIMITPOELYTS EFIL", "Lifestyle"),
        WordScramblePuzzle(372, "HOLISTICWELLBEING", "GNIEBLLEW CITSILOH", "Lifestyle"),
        WordScramblePuzzle(373, "ENTREPRENEURSHIP", "PIHSRUENEPERTNE", "Business"),
        WordScramblePuzzle(374, "VENTURECAPITAL", "LATIPACE RUTNEV", "Business"),
        WordScramblePuzzle(375, "STRATEGICPLANNING", "GNINNALPCIGETARTS", "Business"),
        WordScramblePuzzle(376, "ORGANIZATIONALBEHAVIOR", "ROIVAHEBLANOITAZINAGRO", "Business"),
        WordScramblePuzzle(377, "GLOBALSUPPLYNETWORK", "KROWTENYLPPUSLABOLG", "Business"),
        WordScramblePuzzle(378, "MULTIMODALTRANSPORT", "TROPSNARTLADOMITLUM", "Transport"),
        WordScramblePuzzle(379, "INTELLIGENTTRAFFIC", "CIFFARTTNEGILLETNI", "Transport"),
        WordScramblePuzzle(380, "AUTONOMOUSVEHICLE", "ELCIHEV SUOMONOTUA", "Transport"),
        WordScramblePuzzle(381, "SUSTAINABLEMOBILITY", "YTILIBOMELBAN IATSUS", "Transport"),
        WordScramblePuzzle(382, "EDUCATIONALTECHNOLOGY", "YGOLOHCETLANOITACUDE", "Education"),
        WordScramblePuzzle(383, "INSTRUCTIONALDESIGN", "NGISEDLANOITCURTSNI", "Education"),
        WordScramblePuzzle(384, "PEDAGOGICALMETHODS", "SDOHTEMLACIGOGADEP", "Education"),
        WordScramblePuzzle(385, "LIFELONGLEARNING", "GNINRAELGNOL EFIL", "Education"),
        WordScramblePuzzle(386, "ACADEMICRESEARCH", "HCRAESERCIMEDACA", "Education"),
        WordScramblePuzzle(387, "PROFESSIONALDEVELOPMENT", "TNEMPOLEVEDLANOISSEFORP", "Business"),
        WordScramblePuzzle(388, "WORKLIFEBALANCE", "ECNALABEFILKROW", "Lifestyle"),
        WordScramblePuzzle(389, "PRODUCTIVITYSYSTEMS", "SMETSYSYTIVITCUDORP", "Lifestyle"),
        WordScramblePuzzle(390, "FINANCIALINDEPENDENCE", "ECNEDNEPEDNIL AICNANIF", "Lifestyle"),
        WordScramblePuzzle(391, "URBANINFRASTRUCTURE", "ERUTCARTSNI N ABRU", "Transport"),
        WordScramblePuzzle(392, "TRANSPORTATIONPLANNING", "GNINNALPNOITATROPSNART", "Transport"),
        WordScramblePuzzle(393, "SMARTCITYSOLUTIONS", "SNOITULOSYTIC TRAMS", "Transport"),
        WordScramblePuzzle(394, "LEARNINGANALYTICS", "SCITYLANA GNINRAEL", "Education"),
        WordScramblePuzzle(395, "COMPETENCYBASEDLEARNING", "GNINRAELDESABYTCNEPETMOC", "Education"),
        WordScramblePuzzle(396, "EXECUTIVELEADERSHIP", "PIHSREDAEL EVITUCEXE", "Business"),
        WordScramblePuzzle(397, "DIGITALTRANSFORMATION", "NOITAMROFSNARTLATIGID", "Business"),
        WordScramblePuzzle(398, "REMOTEWORKCULTURE", "ERUTLUC KROWTOMER", "Lifestyle"),
        WordScramblePuzzle(399, "CAREERSTRATEGY", "YGETARTS REERAC", "Business"),
        WordScramblePuzzle(400, "EDUCATIONALECOSYSTEM", "METSYSOCE LANOITACUDE", "Education"),

        WordScramblePuzzle(401, "PHILOSOPHICAL", "LACIHOSOPOHPLI", "Culture"),
        WordScramblePuzzle(402, "CULTURALGLOBALIZATION", "NOITAZILABOLGRUTLUC", "Culture"),
        WordScramblePuzzle(403, "POSTMODERNISM", "MSINREDOMTSOP", "Culture"),
        WordScramblePuzzle(404, "HISTORICALREVISIONISM", "MSIN OISIVERLACIROTSIH", "History"),
        WordScramblePuzzle(405, "ANTHROPOLOGY", "YGLOPORHTNA", "History"),
        WordScramblePuzzle(406, "GEOPOLITICS", "SCITILOP OEG", "History"),
        WordScramblePuzzle(407, "PALEONTOLOGY", "YGLOTNOELAP", "Science"),
        WordScramblePuzzle(408, "ASTROBIOLOGY", "YGLOIBORTSA", "Science"),
        WordScramblePuzzle(409, "QUANTUMMECHANICS", "SCINAHCEMMUTNAUQ", "Science"),
        WordScramblePuzzle(410, "RELATIVITYTHEORY", "YROEHTYTIVITALER", "Science"),
        WordScramblePuzzle(
            411,
            "ENVIRONMENTALSUSTAINABILITY",
            "YTILIBANIATSUSLATNEMNORIVNE",
            "Nature"
        ),
        WordScramblePuzzle(412, "CONSERVATIONBIOLOGY", "YGLOIBNOITAVRESNOC", "Nature"),
        WordScramblePuzzle(413, "METEOROLOGICALPHENOMENA", "ANEMONEHP LACIGOLOETEOREM", "Nature"),
        WordScramblePuzzle(414, "HYDROELECTRICPOWER", "REWOPCIRTCELEORDYH", "Nature"),
        WordScramblePuzzle(415, "ECOSYSTEMREGENERATION", "NOITARENEGERMETSYSOCE", "Nature"),
        WordScramblePuzzle(416, "ETHNOMUSICOLOGY", "YGLOOCISUMONHTE", "Music"),
        WordScramblePuzzle(417, "POLYPHONICCOMPOSITION", "NOITISOPMOCCINOHYLOP", "Music"),
        WordScramblePuzzle(418, "CONTEMPORARYCLASSICAL", "LACISSALCRAYROPMETNOC", "Music"),
        WordScramblePuzzle(419, "SOUNDENGINEERING", "GNIREENIGNEDNUOS", "Music"),
        WordScramblePuzzle(420, "ELECTROACOUSTIC", "CITSUOCAORTCELE", "Music"),
        WordScramblePuzzle(421, "URBANPLANNING", "GNINNALPNABRU", "Places"),
        WordScramblePuzzle(422, "MEGACITYINFRASTRUCTURE", "ERUTCARTSNIYTICAGEM", "Places"),
        WordScramblePuzzle(423, "TRANSCONTINENTAL", "LATNENITNOCTSNART", "Transport"),
        WordScramblePuzzle(424, "INTERMODALLOGISTICS", "SCITSIGOLLADOMRETNI", "Transport"),
        WordScramblePuzzle(425, "AUTONOMOUSNAVIGATION", "NOITAGIVANSUOMONOTUA", "Transport"),
        WordScramblePuzzle(426, "AEROSPACEENGINEERING", "GNIREENIGNECAPSOREA", "Technology"),
        WordScramblePuzzle(427, "DISTRIBUTEDCOMPUTING", "GNITUPMOCD ETUBIRTSID", "Technology"),
        WordScramblePuzzle(
            428,
            "ARTIFICIALGENERALINTELLIGENCE",
            "ECNEGILLETNI LARENEG LAICIFITRA",
            "Technology"
        ),
        WordScramblePuzzle(
            429,
            "CYBERSECURITYARCHITECTURE",
            "ERUTCETHCRA YTIRUCESREBYC",
            "Technology"
        ),
        WordScramblePuzzle(430, "BLOCKCHAINGOVERNANCE", "ECNANREVOGNIAHCKCOLB", "Technology"),

        // ---------- MASTER LEVEL (431–470) ----------
        WordScramblePuzzle(
            431,
            "CORPORATESTRATEGYFORMULATION",
            "NOITALUMROFYGETARTSE TAROPROC",
            "Business"
        ),
        WordScramblePuzzle(432, "BEHAVIORALECONOMICS", "SCIMONOCE LAROIVAH EB", "Business"),
        WordScramblePuzzle(433, "MACROECONOMICINDICATORS", "SROTACIDNIMONOC EORCAM", "Business"),
        WordScramblePuzzle(434, "GLOBALMARKETPENETRATION", "NOITARTENEPTEKRAMLABOLG", "Business"),
        WordScramblePuzzle(435, "VENTURESCALABILITY", "YTILIBALACSERUTNEV", "Business"),
        WordScramblePuzzle(
            436,
            "PERSONALDEVELOPMENTFRAMEWORK",
            "KROWEMARF TNEMPOLEVEDLANOSREP",
            "Lifestyle"
        ),
        WordScramblePuzzle(437, "HUMANCENTEREDDESIGN", "NGISED DERETNECNAMUH", "Lifestyle"),
        WordScramblePuzzle(438, "MENTALRESILIENCE", "ECNEILISERLATNEM", "Lifestyle"),
        WordScramblePuzzle(439, "BEHAVIORALPSYCHOLOGY", "YGLOHCOYSP LAROIVAH EB", "Lifestyle"),
        WordScramblePuzzle(440, "LONGTERMGOALSETTING", "GNITTESLAOGMRETGNOL", "Lifestyle"),
        WordScramblePuzzle(441, "EDUCATIONALPOLICYREFORM", "MROFERYCILOPLANOITACUDE", "Education"),
        WordScramblePuzzle(
            442,
            "COGNITIVESCIENCERESEARCH",
            "HCRAESERECN EICS EVITIN GOC",
            "Education"
        ),
        WordScramblePuzzle(443, "CURRICULUMARCHITECTURE", "ERUTCETHCRAMULU C IRUC", "Education"),
        WordScramblePuzzle(444, "ASSESSMENTMETHODOLOGY", "YGLODOHTEMTNEMSSESA", "Education"),
        WordScramblePuzzle(
            445,
            "LEARNINGSCIENCEFRAMEWORK",
            "KROWEMARFECNEICS GNINRAEL",
            "Education"
        ),
        WordScramblePuzzle(
            446,
            "INTERDISCIPLINARYRESEARCH",
            "HCRAESERYRANILPICSDRETNI",
            "Education"
        ),
        WordScramblePuzzle(
            447,
            "CROSSCULTURALCOMMUNICATION",
            "NOITACINUMMOCLARUTLU S SOC",
            "Culture"
        ),
        WordScramblePuzzle(448, "HISTORICALCONSCIOUSNESS", "SSEN SUOICSNOC LACIROSITH", "History"),
        WordScramblePuzzle(449, "GLOBALCIVILIZATIONSTUDY", "YDUTSNOITAZILIVICLABOLG", "History"),
        WordScramblePuzzle(450, "ARCHIVALDOCUMENTATION", "NOITATNEMUCODLAVIHCRA", "History"),
        WordScramblePuzzle(
            451,
            "PLANETARYSYSTEMDYNAMICS",
            "SCIMANYD M ETSY S YRATENALP",
            "Science"
        ),
        WordScramblePuzzle(
            452,
            "COMPUTATIONALNEUROSCIENCE",
            "ECNEICSORUEN LANOITATUPMOC",
            "Science"
        ),
        WordScramblePuzzle(
            453,
            "EVOLUTIONARYBIOINFORMATICS",
            "SCITAMROFNIONOIBYROITULOVE",
            "Science"
        ),
        WordScramblePuzzle(
            454,
            "CLIMATEADAPTATIONSTRATEGY",
            "YGETARTSNOITATPAD E TAM ILC",
            "Nature"
        ),
        WordScramblePuzzle(455, "PLANETARYBOUNDARIES", "SEIRADNUOBYRATENALP", "Nature"),
        WordScramblePuzzle(456, "SUSTAINABLEECONOMYMODEL", "LEDOMYMONOCEELBAN IATSUS", "Nature"),
        WordScramblePuzzle(457, "EXPERIMENTALCOMPOSITION", "NOITISOPM OCLATNEMIREPXE", "Music"),
        WordScramblePuzzle(458, "SYMPHONICORCHESTRATION", "NOITARTSEHCRO CINOHP MYS", "Music"),
        WordScramblePuzzle(459, "ADVANCEDMUSICTHEORY", "YROEHTCISUMDECNAVDA", "Music"),
        WordScramblePuzzle(
            460,
            "DIGITALAUDIOSIGNALPROCESSING",
            "GNISSECORPLAN GIS O IDUA LATIGID",
            "Music"
        ),

        // ---------- LEGENDARY (461–500) ----------
        WordScramblePuzzle(
            461,
            "TRANSPORTATIONECOSYSTEMDESIGN",
            "NGISEDMETSYSOECNOITATROPSNART",
            "Transport"
        ),
        WordScramblePuzzle(
            462,
            "GLOBALMOBILITYINFRASTRUCTURE",
            "ERUTCARTSNIYTILIBOMLABOLG",
            "Transport"
        ),
        WordScramblePuzzle(
            463,
            "SMARTCITYTRANSPORTNETWORKS",
            "SKROWTENTROPSNARTYTIC TRAMS",
            "Transport"
        ),
        WordScramblePuzzle(
            464,
            "INTELLIGENTTRAFFICOPTIMIZATION",
            "NOITAZIMITPOCIFFARTTNEGILLETNI",
            "Transport"
        ),
        WordScramblePuzzle(
            465,
            "NEXTGENERATIONLEARNINGPLATFORMS",
            "SMROFTALPGNINRAELNOITARENEG TXEN",
            "Education"
        ),
        WordScramblePuzzle(
            466,
            "AIASSISTEDEDUCATIONALSYSTEMS",
            "SMETSYS LANOITACUDEDETSISSAIA",
            "Education"
        ),
        WordScramblePuzzle(
            467,
            "KNOWLEDGECAPITALFORMATION",
            "NOITAMROFLATIPACEGDELWONK",
            "Education"
        ),
        WordScramblePuzzle(468, "FUTUREOFWORKANDLEARNING", "GNINRAELDNAKROWFOERUTUF", "Business"),
        WordScramblePuzzle(
            469,
            "DIGITALECONOMYTRANSFORMATION",
            "NOITAMROFSNARTYMONOEC LATIGID",
            "Business"
        ),
        WordScramblePuzzle(
            470,
            "GLOBALINNOVATIONECOSYSTEM",
            "METSYSOECNOITAVONNILABOLG",
            "Business"
        ),
        WordScramblePuzzle(471, "HYPERCONNECTEDLIFESTYLE", "ELYTS EFILDETCENNOCREPYH", "Lifestyle"),
        WordScramblePuzzle(472, "TECHNOMINALISM", "MSILANIMONHCET", "Lifestyle"),
        WordScramblePuzzle(473, "FUTURISTICURBANLIVING", "GNIVILNABRUCITSIRUTUF", "Lifestyle"),
        WordScramblePuzzle(
            474,
            "COGNITIVELOADMANAGEMENT",
            "TNEMEGANAMDAOL EVIT INGOC",
            "Lifestyle"
        ),
        WordScramblePuzzle(
            475,
            "HUMANPOTENTIALOPTIMIZATION",
            "NOITAZIMITOPLAITNETOPNAMUH",
            "Lifestyle"
        ),
        WordScramblePuzzle(476, "TRANSCULTURALIDENTITY", "YTITNEDILARUTLUCTSNART", "Culture"),
        WordScramblePuzzle(
            477,
            "GLOBALHERITAGECONSERVATION",
            "NOITAVRESNOC EGATIREHLABOLG",
            "Culture"
        ),
        WordScramblePuzzle(478, "POSTCOLONIALSTUDIES", "SEIDUTSLAINOLOC TSOP", "History"),
        WordScramblePuzzle(
            479,
            "LONGITUDINALHISTORICALANALYSIS",
            "SISYLANA LACIROSITHLANIDUTIGNOL",
            "History"
        ),
        WordScramblePuzzle(480, "SYSTEMSECOLOGYMODEL", "LEDOMYGLOCOEC SMETSYS", "Nature"),
        WordScramblePuzzle(481, "PLANETARYCLIMATEFEEDBACK", "KCABDEEFETAMILCYRATENALP", "Nature"),
        WordScramblePuzzle(482, "EXTREMEEVENTATTRIBUTION", "NOITUBIRTTA TNEVEE MERTXE", "Nature"),
        WordScramblePuzzle(
            483,
            "ADVANCEDCOMPOSITIONTECHNIQUES",
            "SEUQINHCETNOITISOPMOCDECNAVDA",
            "Music"
        ),
        WordScramblePuzzle(
            484,
            "ALGORITHMICMUSICGENERATION",
            "NOITARENEG C ISU M C I M HT I R O G L A",
            "Music"
        ),
        WordScramblePuzzle(
            485,
            "HUMANCOMPUTERINTERACTIONDESIGN",
            "NGISEDNOITCARETNI RETUPMO C NAMUH",
            "Technology"
        ),
        WordScramblePuzzle(
            486,
            "COGNITIVEARCHITECTURESYSTEMS",
            "SMETSYSERUTCETHCRA EVIT INGOC",
            "Technology"
        ),
        WordScramblePuzzle(
            487,
            "QUANTUMINFORMATIONPROCESSING",
            "GNISSECORPNOITAMROFNIMUMTNAUQ",
            "Technology"
        ),
        WordScramblePuzzle(
            488,
            "POSTDIGITALTRANSFORMATIONERA",
            "ARENOITAMROFSNARTLATIGIDTSOP",
            "Technology"
        ),
        WordScramblePuzzle(
            489,
            "GLOBALTECHNOLOGYGOVERNANCE",
            "ECNANREVOGYGOLOH C E T LABOLG",
            "Technology"
        ),
        WordScramblePuzzle(
            490,
            "EDUCATIONFUTUREECOSYSTEM",
            "METSYSOECERUTUFNOITACUDE",
            "Education"
        ),
        WordScramblePuzzle(
            491,
            "METACOGNITIVELEARNINGSTRATEGIES",
            "SEIGETARTSGNINRAEL EVIT INGOCATEM",
            "Education"
        ),
        WordScramblePuzzle(
            492,
            "ADAPTIVEINTELLIGENTTUTORING",
            "GNIROTUTTNEGILLETNIEVITPAD A",
            "Education"
        ),
        WordScramblePuzzle(
            493,
            "GLOBALTRANSPORTOPTIMIZATION",
            "NOITAZIMITOPTROPSNARTLABOLG",
            "Transport"
        ),
        WordScramblePuzzle(
            494,
            "NEXTGENMOBILITYSOLUTIONS",
            "SNOITULOSYTILIBOMNEG TXEN",
            "Transport"
        ),
        WordScramblePuzzle(
            495,
            "INTERPLANETARYTRANSPORTSYSTEMS",
            "SMETSYSTROPSNARTYRATENALPRETNI",
            "Transport"
        ),
        WordScramblePuzzle(
            496,
            "PERSONALKNOWLEDGEMANAGEMENT",
            "TNEMEGANAMEGDELWONKLANOSREP",
            "Lifestyle"
        ),
        WordScramblePuzzle(
            497,
            "DIGITALMINIMALISMLIFESTYLE",
            "ELYTS EFILMSILANIMLATIGID",
            "Lifestyle"
        ),
        WordScramblePuzzle(
            498,
            "GLOBALSTRATEGICLEADERSHIP",
            "PIHSREDAELCIGETARTSLABOLG",
            "Business"
        ),
        WordScramblePuzzle(
            499,
            "FUTUREECONOMICSYSTEMDESIGN",
            "NGISEDMETSYSMONOCEERUTUF",
            "Business"
        ),
        WordScramblePuzzle(500, "INTERDISCIPLINARYMASTERY", "YRETSAMYRANILPICSDRETNI", "Education")


    )

    fun getPuzzleForLevel(level: Int): WordScramblePuzzle {
        // Levels may exceed the size of puzzles list; wrap around or clamp as needed.
        val idx = (level - 1).coerceIn(0, puzzles.size - 1)
        return puzzles[idx]
    }
}

